export class Element {
  constructor(
    public z: number,
    public symbol: string,
    public name: string,
    public color?: string,
  ) {}

  get label(): string {
    return `${this.z} - ${this.symbol} - ${this.name}`;
  }
}

export const elements = [
  new Element(3, "Li", "Lithium"),
  new Element(4, "Be", "Beryllium"),
  new Element(5, "B", "Boron"),
  new Element(6, "C", "Carbon"),
  new Element(7, "N", "Nitrogen"),
  new Element(8, "O", "Oxygen"),
  new Element(9, "F", "Fluorine"),
  new Element(10, "Ne", "Neon"),
  new Element(11, "Na", "Sodium"),
  new Element(12, "Mg", "Magnesium"),
  new Element(13, "Al", "Aluminum"),
  new Element(14, "Si", "Silicon"),
  new Element(15, "P", "Phosphorus"),
  new Element(16, "S", "Sulfur"),
  new Element(17, "Cl", "Chlorine"),
  new Element(18, "Ar", "Argon"),
  new Element(19, "K", "Potassium"),
  new Element(20, "Ca", "Calcium"),
  new Element(21, "Sc", "Scandium"),
  new Element(22, "Ti", "Titanium"),
  new Element(23, "V", "Vanadium"),
  new Element(24, "Cr", "Chromium"),
  new Element(25, "Mn", "Manganese"),
  new Element(26, "Fe", "Iron"),
  new Element(27, "Co", "Cobalt"),
  new Element(28, "Ni", "Nickel"),
  new Element(29, "Cu", "Copper"),
  new Element(30, "Zn", "Zinc"),
  new Element(31, "Ga", "Gallium"),
  new Element(32, "Ge", "Germanium"),
  new Element(33, "As", "Arsenic"),
  new Element(34, "Se", "Selenium"),
  new Element(35, "Br", "Bromine"),
  new Element(36, "Kr", "Krypton"),
  new Element(37, "Rb", "Rubidium"),
  new Element(38, "Sr", "Strontium"),
  new Element(39, "Y", "Yttrium"),
  new Element(40, "Zr", "Zirconium"),
  new Element(41, "Nb", "Niobium"),
  new Element(42, "Mo", "Molybdenum"),
  new Element(43, "Tc", "Technetium"),
  new Element(44, "Ru", "Ruthenium"),
  new Element(45, "Rh", "Rhodium"),
  new Element(46, "Pd", "Palladium"),
  new Element(47, "Ag", "Silver"),
  new Element(48, "Cd", "Cadmium"),
  new Element(49, "In", "Indium"),
  new Element(50, "Sn", "Tin"),
  new Element(51, "Sb", "Antimony"),
  new Element(52, "Te", "Tellurium"),
  new Element(53, "I", "Iodine"),
  new Element(54, "Xe", "Xenon"),
  new Element(55, "Cs", "Cesium"),
  new Element(56, "Ba", "Barium"),
  new Element(57, "La", "Lanthanum"),
  new Element(58, "Ce", "Cerium"),
  new Element(59, "Pr", "Praseodymium"),
  new Element(60, "Nd", "Neodymium"),
  new Element(61, "Pm", "Promethium"),
  new Element(62, "Sm", "Samarium"),
  new Element(63, "Eu", "Europium"),
  new Element(64, "Gd", "Gadolinium"),
  new Element(65, "Tb", "Terbium"),
  new Element(66, "Dy", "Dysprosium"),
  new Element(67, "Ho", "Holmium"),
  new Element(68, "Er", "Erbium"),
  new Element(69, "Tm", "Thulium"),
  new Element(70, "Yb", "Ytterbium"),
  new Element(71, "Lu", "Lutetium"),
  new Element(72, "Hf", "Hafnium"),
  new Element(73, "Ta", "Tantalum"),
  new Element(74, "W", "Tungsten"),
  new Element(75, "Re", "Rhenium"),
  new Element(76, "Os", "Osmium"),
  new Element(77, "Ir", "Iridium"),
  new Element(78, "Pt", "Platinum"),
  new Element(79, "Au", "Gold"),
  new Element(80, "Hg", "Mercury"),
  new Element(81, "Tl", "Thallium"),
  new Element(82, "Pb", "Lead"),
  new Element(83, "Bi", "Bismuth"),
  new Element(84, "Po", "Polonium"),
  new Element(85, "At", "Astatine"),
  new Element(86, "Rn", "Radon"),
  new Element(87, "Fr", "Francium"),
  new Element(88, "Ra", "Radium"),
  new Element(89, "Ac", "Actinium"),
  new Element(90, "Th", "Thorium"),
  new Element(91, "Pa", "Protactinium"),
  new Element(92, "U", "Uranium"),
];
